ALTER TABLE adminapp.SecretConfigurations ADD OdsInstanceRegistrationId INT NULL;
ALTER TABLE adminapp.SecretConfigurations ADD CONSTRAINT FK_SecretConfigurations_OdsInstanceRegistrations_Id FOREIGN KEY (OdsInstanceRegistrationId) REFERENCES adminapp.OdsInstanceRegistrations (Id);
